# Generated by Django 5.2.8 on 2025-11-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
